package gha

var (
	archSuffixes = []string{
		"-linux-amd64",
		"-linux-arm64",
		"-windows-amd64",
		"-windows-arm64",
		"-windows-ltsc2022-amd64",
		"-windows-ltsc2022-arm64",
		"-windows-1809-amd64",
		"-windows-1809-arm64",
		"-amd64",
		"-arm64",
		"-s390x",
	}

	// imageRepo holds the mappings between container image and source code repositories.
	imageRepo = map[string]string{
		"rancher/rancher-csp-adapter":                         "rancher/csp-adapter",
		"rancher/fleet-agent":                                 "rancher/fleet",
		"rancher/rke2-runtime":                                "rancher/rke2",
		"rancher/rke2-cloud-provider":                         "rancher/image-build-rke2-cloud-provider",
		"rancher/hardened-addon-resizer":                      "rancher/image-build-addon-resizer",
		"rancher/hardened-calico":                             "rancher/image-build-calico",
		"rancher/hardened-cluster-autoscaler":                 "rancher/image-build-cluster-proportional-autoscaler",
		"rancher/hardened-whereabouts":                        "rancher/image-build-whereabouts",
		"rancher/hardened-node-feature-discovery":             "rancher/image-build-node-feature-discovery",
		"rancher/hardened-multus-cni":                         "rancher/image-build-multus",
		"rancher/hardened-multus-thick":                       "rancher/image-build-multus",
		"rancher/hardened-multus-dynamic-networks-controller": "rancher/image-build-multus-dynamic-networks-controller",
		"rancher/hardened-kubernetes":                         "rancher/image-build-kubernetes",
		"rancher/hardened-k8s-metrics-server":                 "rancher/image-build-k8s-metrics-server",
		"rancher/hardened-flannel":                            "rancher/image-build-flannel",
		"rancher/hardened-etcd":                               "rancher/image-build-etcd",
		"rancher/hardened-dns-node-cache":                     "rancher/image-build-dns-nodecache",
		"rancher/hardened-coredns":                            "rancher/image-build-coredns",
		"rancher/hardened-cni-plugins":                        "rancher/image-build-cni-plugins",
		"rancher/hardened-traefik":                            "rancher/image-build-traefik",
		"rancher/hardened-csi-snapshotter":                    "rancher/image-build-external-snapshotter",
		"rancher/hardened-snapshot-controller":                "rancher/image-build-external-snapshotter",
		"rancher/hardened-vsphere-csi-syncer":                 "rancher/image-build-vsphere-csi-driver",
		"rancher/nginx-ingress-controller":                    "rancher/ingress-nginx",
		"rancher/nginx-ingress-controller-chroot":             "rancher/ingress-nginx",
		"rancher/kube-webhook-certgen":                        "rancher/ingress-nginx",
		"rancher/pushprox":                                    "rancher/PushProx",
		"rancher/rancher":                                     "rancher/rancher-prime",
		"rancher/rancher-agent":                               "rancher/rancher-prime",
		"rancher/system-agent-installer-rancher":              "rancher/rancher-prime",
		"rancher/rancher-webhook":                             "rancher/webhook",
		"rancher/neuvector-manager":                           "neuvector/manager",
		"rancher/neuvector-controller":                        "neuvector/neuvector",
		"rancher/neuvector-enforcer":                          "neuvector/neuvector",
		"rancher/neuvector-scanner":                           "neuvector/scanner",
		"rancher/neuvector-prometheus-exporter":               "neuvector/prometheus-exporter",
		"rancher/neuvector-registry-adapter":                  "neuvector/registry-adapter",
		"rancher/neuvector-updater":                           "neuvector/updater",
		"rancher/neuvector-compliance-config":                 "neuvector/compliance-config",
		"rancher/supportability-review-internal":              "rancher/supportability-review",
		"rancher/supportability-review-app-frontend":          "rancher/supportability-review-operator",
		"rancher/cluster-api-provider-rke2-bootstrap":         "rancher/cluster-api-provider-rke2",
		"rancher/cluster-api-provider-rke2-controlplane":      "rancher/cluster-api-provider-rke2",
		"harvester/harvester-lvm-csi-plugin":                  "harvester/csi-driver-lvm",
		"harvester/harvester-lvm-provisioner":                 "harvester/csi-driver-lvm",
		"harvester/harvester-lvm-csi-driver-webhook":          "harvester/csi-driver-lvm",
		"harvester/support-bundle-kit":                        "rancher/support-bundle-kit",
		"harvester/harvester-kubeovn-operator":                "harvester/kubeovn-operator",
		"harvester/harvester-eventrouter":                     "harvester/eventrouter",
		"harvester/harvester-ansible-operator":                "harvester/forklift-packaging",
		"harvester/harvester-forklift-api":                    "harvester/forklift-packaging",
		"harvester/harvester-forklift-controller":             "harvester/forklift-packaging",
		"harvester/harvester-forklift-operator":               "harvester/forklift-packaging",
		"harvester/harvester-openstack-populator":             "harvester/forklift-packaging",
		"harvester/harvester-ova-provider-server":             "harvester/forklift-packaging",
		"harvester/harvester-ovirt-populator":                 "harvester/forklift-packaging",
		"harvester/harvester-populator-controller":            "harvester/forklift-packaging",
		"harvester/harvester-validation":                      "harvester/forklift-packaging",
		"harvester/harvester-virt-v2v":                        "harvester/forklift-packaging",
		"harvester/harvester-vsphere-xcopy-populator":         "harvester/forklift-packaging",
		"harvester/harvester-load-balancer":                   "harvester/load-balancer-harvester",
		"harvester/harvester-load-balancer-webhook":           "harvester/load-balancer-harvester",
		"harvester/harvester-network-controller":              "harvester/network-controller-harvester",
		"harvester/harvester-network-helper":                  "harvester/network-controller-harvester",
		"harvester/harvester-network-webhook":                 "harvester/network-controller-harvester",
		"harvester/harvester-networkfs-manager":               "harvester/networkfs-manager",
		"harvester/harvester-node-disk-manager":               "harvester/node-disk-manager",
		"harvester/harvester-node-disk-manager-webhook":       "harvester/node-disk-manager",
		"harvester/harvester-node-manager":                    "harvester/node-manager",
		"harvester/harvester-node-manager-webhook":            "harvester/node-manager",
		"harvester/harvester-nvidia-driver-toolkit":           "harvester/os2",
		"harvester/harvester-os":                              "harvester/os2",
		"harvester/harvester-kernel-module-devel":             "harvester/os2",
		"harvester/harvester-pcidevices":                      "harvester/pcidevices",
		"harvester/harvester-seeder":                          "harvester/seeder",
		"harvester/harvester-vm-import-controller":            "harvester/vm-import-controller",
		"harvester/harvester":                                 "harvester/harvester",
		"harvester/harvester-webhook":                         "harvester/harvester",
		"harvester/harvester-upgrade":                         "harvester/harvester",
		"harvester/harvester-cluster-repo":                    "harvester/harvester",
	}

	mutableRepo = map[string]bool{
		"rancher/neuvector-scanner:6": true,
	}

	identityOverride = map[string]string{
		"rancher/azureserviceoperator":                                    "^https://github.com/rancher/clusterapi-forks/.github/workflows/azure-service-operator.yaml@refs/heads/main$",
		"rancher/cluster-api-addon-provider-fleet":                        "^https://github.com/rancher/clusterapi-forks/.github/workflows/caapf.yaml@refs/heads/main$",
		"rancher/cluster-api-controller":                                  "^https://github.com/rancher/clusterapi-forks/.github/workflows/core.yaml@refs/heads/main$",
		"rancher/kubeadm-bootstrap-controller":                            "^https://github.com/rancher/clusterapi-forks/.github/workflows/core.yaml@refs/heads/main$",
		"rancher/kubeadm-control-plane-controller":                        "^https://github.com/rancher/clusterapi-forks/.github/workflows/core.yaml@refs/heads/main$",
		"rancher/cluster-api-aws-controller":                              "^https://github.com/rancher/clusterapi-forks/.github/workflows/aws.yaml@refs/heads/main$",
		"rancher/cluster-api-azure-controller":                            "^https://github.com/rancher/clusterapi-forks/.github/workflows/azure.yaml@refs/heads/main$",
		"rancher/cluster-api-gcp-controller":                              "^https://github.com/rancher/clusterapi-forks/.github/workflows/gcp.yaml@refs/heads/main$",
		"rancher/cluster-api-vsphere-controller":                          "^https://github.com/rancher/clusterapi-forks/.github/workflows/vsphere.yaml@refs/heads/main$",
		"rancher/cluster-api-provider-metal3":                             "^https://github.com/rancher/clusterapi-forks/.github/workflows/metal3.yaml@refs/heads/main$",
		"rancher/ip-address-manager":                                      "^https://github.com/rancher/clusterapi-forks/.github/workflows/metal3-ipam.yaml@refs/heads/main$",
		"rancher/mirrored-cilium-cilium":                                  "^https://github.com/cilium/cilium/.github/workflows/build-images-releases.yaml@refs/tags/v",
		"rancher/mirrored-cilium-envoy":                                   "^https://github.com/cilium/proxy/.github/workflows/build-envoy-images-release.yaml@refs/heads/v",
		"rancher/mirrored-cilium-clustermesh-apiserver":                   "^https://github.com/cilium/cilium/.github/workflows/build-images-releases.yaml@refs/tags/v",
		"rancher/mirrored-cilium-hubble-relay":                            "^https://github.com/cilium/cilium/.github/workflows/build-images-releases.yaml@refs/tags/v",
		"rancher/mirrored-cilium-operator-aws":                            "^https://github.com/cilium/cilium/.github/workflows/build-images-releases.yaml@refs/tags/v",
		"rancher/mirrored-cilium-operator-azure":                          "^https://github.com/cilium/cilium/.github/workflows/build-images-releases.yaml@refs/tags/v",
		"rancher/mirrored-cilium-operator-generic":                        "^https://github.com/cilium/cilium/.github/workflows/build-images-releases.yaml@refs/tags/v",
		"rancher/mirrored-prometheus-operator-prometheus-config-reloader": "^https://github.com/prometheus-operator/prometheus-operator/.github/workflows/publish.yaml@refs/tags/v",
		"rancher/mirrored-kube-logging-logging-operator":                  "^https://github.com/kube-logging/logging-operator/.github/workflows/artifacts.yaml@refs/tags/",
		"rancher/image-build-etcd":                                        "^https://github.com/rancher/image-build-etcd/.github/workflows/(image-push|release).yml@refs/tags/v",
		"rancher/image-build-whereabouts":                                 "^https://github.com/rancher/image-build-whereabouts/.github/workflows/(image-push|release).yml@refs/tags/v",
		"rancher/image-build-rke2-cloud-provider":                         "^https://github.com/rancher/image-build-rke2-cloud-provider/.github/workflows/(image-push|release).yml@refs/tags/v",
		"rancher/image-build-cni-plugins":                                 "^https://github.com/rancher/image-build-cni-plugins/.github/workflows/(image-push|release).yml@refs/tags/v",
		"rancher/pushprox":                                                "^https://github.com/rancher/PushProx/.github/workflows/release.ya?ml@refs/tags/v",
		"rancher/supportability-review":                                   "^https://github.com/rancher/supportability-review/.github/workflows/release.yaml@refs/tags/v",
		"rancher/supportability-review-operator":                          "^https://github.com/rancher/supportability-review-operator/.github/workflows/release.yaml@refs/tags/v",
		"rancher/rancher-prime":                                           "^https://github.com/rancher/rancher-prime/.github/workflows/(release|alpha-release|rc-release).yml@refs/tags/v",
		"rancher/rancher-webhook":                                         "^https://github.com/rancher/webhook/.github/workflows/release.ya?ml@refs/tags/v",
		"rancher/prometheus-federator":                                    "^https://github.com/rancher/prometheus-federator/.github/workflows/(release|publish).yaml@refs/tags/v",
		"rancher/turtles":                                                 "^https://github.com/rancher/turtles/.github/workflows/(release-v2|release).ya?ml@refs/tags/v",
		"kubewarden/policy-server":                                        "^https://github.com/kubewarden/(policy-server|kubewarden-controller)/.github/workflows/release.ya?ml@refs/tags/v",
		"kubewarden/audit-scanner":                                        "^https://github.com/kubewarden/(audit-scanner|kubewarden-controller)/.github/workflows/release.ya?ml@refs/tags/v",
		"adm-controller/policy-server":                                    "^https://github.com/kubewarden/adm-controller/.github/workflows/release.ya?ml@refs/tags/v",
		"adm-controller/audit-scanner":                                    "^https://github.com/kubewarden/adm-controller/.github/workflows/release.ya?ml@refs/tags/v",
		"adm-controller/controller":                                       "^https://github.com/kubewarden/adm-controller/.github/workflows/release.ya?ml@refs/tags/v",
		"harvester/harvester-mcp-server":                                  "^https://github.com/harvester/harvester-mcp-server/.github/workflows/release.yml@refs/(heads/(main|v.*)|tags/v.*)$",
		"harvester/csi-driver-lvm":                                        "^https://github.com/harvester/csi-driver-lvm/.github/workflows/factory.yml@refs/(heads/(main|v.*)|tags/prime-.*)$",
		"rancher/support-bundle-kit":                                      "^https://github.com/rancher/support-bundle-kit/.github/workflows/template-build.yml@refs/(heads/master|tags/v.*)$",
		"harvester/kubeovn-operator":                                      "^https://github.com/harvester/kubeovn-operator/.github/workflows/template-build.yml@refs/(heads/(main|v.*|release-.*)|tags/prime-.*)$",
		"harvester/eventrouter":                                           "^https://github.com/harvester/eventrouter/.github/workflows/factory.yml@refs/(heads/(master|v.*)|tags/prime-.*)$",
		"harvester/forklift-packaging":                                    "^https://github.com/harvester/forklift-packaging/.github/workflows/template-build.yml@refs/(heads/(main|release/v.*|v.*)|tags/v.*)$",
		"harvester/load-balancer-harvester":                               "^https://github.com/harvester/load-balancer-harvester/.github/workflows/template-build.yml@refs/(heads/(master|v.*)|tags/prime-.*)$",
		"harvester/network-controller-harvester":                          "^https://github.com/harvester/network-controller-harvester/.github/workflows/template-build.yml@refs/(heads/(master|v.*)|tags/prime-.*)$",
		"harvester/networkfs-manager":                                     "^https://github.com/harvester/networkfs-manager/.github/workflows/factory.yml@refs/(heads/(main|v.*)|tags/prime-.*)$",
		"harvester/node-disk-manager":                                     "^https://github.com/harvester/node-disk-manager/.github/workflows/factory.yaml@refs/(heads/(master|v.*)|tags/prime-.*)$",
		"harvester/node-manager":                                          "^https://github.com/harvester/node-manager/.github/workflows/template-build.yml@refs/(heads/(master|v.*)|tags/prime-.*)$",
		"harvester/os2":                                                   "^https://github.com/harvester/os2/.github/workflows/factory.yml@refs/(heads/(sle-micro|harvester-v.*)|tags/prime-.*)$",
		"harvester/pcidevices":                                            "^https://github.com/harvester/pcidevices/.github/workflows/template-build.yml@refs/(heads/(master|v.*)|tags/prime-.*)$",
		"harvester/seeder":                                                "^https://github.com/harvester/seeder/.github/workflows/template-build.yml@refs/(heads/(main|v.*)|tags/prime-.*)$",
		"harvester/vm-import-controller":                                  "^https://github.com/harvester/vm-import-controller/.github/workflows/template-build.yml@refs/(heads/(main|v.*)|tags/prime-.*)$",
		"harvester/harvester":                                             "^https://github.com/harvester/harvester/.github/workflows/build-factory.yml@refs/(heads/(master|release-.*|v.*)|tags/v.*)$",
	}

	// imageSuffixes holds a mapping between image name and the ref suffixes
	// they may have which will need to be trimmed before defining the expected
	// subject identity.
	imageSuffixes = map[string][]string{
		"rancher/hardened-multus-cni": {"-arch"},
		"rancher/system-agent": {
			"-linux-amd64-suc",
			"-linux-arm64-suc",
			"-suc",
		},
	}
)
