version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - err113
    - errcheck
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocritic
    - lll
    - mnd
    - nestif
    - nlreturn
    - paralleltest
    - revive
    - tagliatelle
    - testifylint
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
