version: 2
project_name: slsactl
builds:
  - id: slsactl
    binary: slsactl
    main: main.go
    flags:
    - -trimpath
    ldflags:
      - -extldflags
      - -s -w
      - -X github.com/rancherlabs/slsactl/cmd.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - formats: [ 'binary', 'tar.gz' ]

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - '--yes'
      - '--new-bundle-format=true' # Remove after bump to cosign v3+
      - '--bundle=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source'
