version: 2
project_name: slsactl
builds:
  - id: slsactl
    binary: slsactl
    main: main.go
    flags:
    - -trimpath
    ldflags:
      - -extldflags
      - -s -w
      - -X github.com/rancherlabs/slsactl/cmd.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - formats: [ 'binary', 'tar.gz' ]

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--yes'
      - '--output-signature=${signature}'
      - '--output-certificate=${certificate}'
      - '--bundle=${artifact}.bundle'
      - '${artifact}'
    artifacts: checksum
    output: true

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source'

release:
  extra_files:
    - glob: ./**/*.bundle
