# This GitHub action install the slsactl CLI, making it available for
# other steps within an GitHub workflow to refer to it.
#
# Reference usage:
#    steps:
#      ...
#      - uses: rancherlabs/slsactl/actions/install-slsactl@main
#        with:
#          version: latest

name: install-slsactl

inputs:
  version:
    description: |
      The slsactl version to be installed.
    required: false
    default: latest
    type: string

runs:
  using: composite

  steps:
  - uses: actions/setup-go@v5
    if: runner.os == 'Windows'
    with:
      go-version: 'stable'

  - name: Install slsactl with go install
    if: runner.os == 'Windows'
    shell: pwsh
    run: |
      go install github.com/rancherlabs/slsactl@${{ inputs.version }}

  - name: Install Cosign
    uses: sigstore/cosign-installer@v3.5.0
    if: runner.os == 'Linux'

  - name: Install slsactl from gh release
    if: runner.os == 'Linux'
    shell: bash
    run: |
      set -x
      if [[ "${VERSION}" == "latest" ]]; then
        echo 'Checking what the latest version is'
        VERSION=$(curl -s 'https://api.github.com/repos/rancherlabs/slsactl/releases/latest' | jq -r '.tag_name')
        
        echo "Using last tag ${VERSION} as version"
      fi

      if [[ "${VERSION}" =~ ^v ]]; then
        echo "Downloading checksum file and signatures for release ${VERSION}"
        curl -LO "https://${REPO}/releases/download/${VERSION}/slsactl_${VERSION#v}_checksums.txt.pem"
        curl -LO "https://${REPO}/releases/download/${VERSION}/slsactl_${VERSION#v}_checksums.txt.sig"
        curl -LO "https://${REPO}/releases/download/${VERSION}/slsactl_${VERSION#v}_checksums.txt"

        cosign verify-blob \
            --certificate-identity "https://${REPO}/.github/workflows/release.yml@refs/tags/${VERSION}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate "slsactl_${VERSION#v}_checksums.txt.pem" \
            --signature "slsactl_${VERSION#v}_checksums.txt.sig" "slsactl_${VERSION#v}_checksums.txt"

        OS="linux"
        if [[ ${RUNNER_OS} != "Linux" ]]; then
            echo "Unsupported OS: ${RUNNER_OS}"
            exit 1
        fi

        ARCH=""
        if [[ $(uname -m) == "x86_64" ]]; then
            ARCH=amd64
        fi
        if [[ $(uname -m) == "aarch64" ]]; then
            ARCH=arm64
        fi

        FILE="slsactl_${VERSION#v}_${OS}_${ARCH}"

        echo "Installing ${FILE}"
        curl -LO "https://${REPO}/releases/download/${VERSION}/${FILE}"
        grep "${FILE}" "slsactl_${VERSION#v}_checksums.txt" | sha256sum -c
      
        chmod +x "${FILE}"
      else
        echo 'Version is not "latest" nor starts with "v". Fallback to go install with commit ID.'
        go install "github.com/rancherlabs/slsactl@${VERSION}"
        FILE="$(go env GOPATH)/bin/slsactl"
      fi

      if sudo -l &> /dev/null; then
        sudo mv "${FILE}" /usr/local/bin/slsactl
      else
        mv "${FILE}" /usr/local/bin/slsactl
      fi
    env:
      VERSION: ${{ inputs.version }}
      REPO: github.com/rancherlabs/slsactl

  - name: Print version
    shell: bash
    run: |
      echo "slsactl installed:"
      slsactl version
