# This GitHub action install the slsactl CLI, making it available for
# other steps within an GitHub workflow to refer to it.
#
# Reference usage:
#    steps:
#      ...
#      - uses: rancherlabs/slsactl/actions/install-slsactl@main
#        with:
#          version: latest

name: install-slsactl

inputs:
  version:
    description: |
      The slsactl version to be installed.
    required: false
    default: latest
    type: string

runs:
  using: composite

  steps:
  - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
    if: runner.os == 'Windows'
    with:
      go-version: 'stable'

  - name: Install slsactl with go install
    if: runner.os == 'Windows'
    shell: bash
    run: |
      VERSION="${{ inputs.version != '' && inputs.version || 'latest' }}"
      go install github.com/rancherlabs/slsactl@${VERSION}

  - name: Install Cosign
    uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
    if: runner.os == 'Linux'

  - name: Install slsactl from gh release
    if: runner.os == 'Linux'
    shell: bash
    run: |
      set -x
      VERSION="${{ inputs.version != '' && inputs.version || 'latest' }}"

      if [[ "${VERSION}" == "latest" ]]; then
        echo 'Checking what the latest version is'
        VERSION=$(curl -s 'https://api.github.com/repos/rancherlabs/slsactl/releases/latest' | jq -r '.tag_name')
        
        echo "Using last tag ${VERSION} as version"
      fi

      if [[ -z "${VERSION}" ]]; then
        echo "WARN: version resolution failed, falling back to @latest"
        VERSION='latest'
      fi

      if [[ "${VERSION}" =~ ^v ]]; then
        echo "Downloading checksum file and signatures for release ${VERSION}"
        curl --retry 3 --retry-connrefused -LO "https://${REPO}/releases/download/${VERSION}/slsactl_${VERSION#v}_checksums.txt.sigstore.json"
        curl --retry 3 --retry-connrefused -LO "https://${REPO}/releases/download/${VERSION}/slsactl_${VERSION#v}_checksums.txt"

        cosign verify-blob \
            --certificate-identity "https://${REPO}/.github/workflows/release.yml@refs/tags/${VERSION}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --new-bundle-format=true \
            --bundle "slsactl_${VERSION#v}_checksums.txt.sigstore.json" "slsactl_${VERSION#v}_checksums.txt"

        OS="linux"
        if [[ ${RUNNER_OS} != "Linux" ]]; then
            echo "Unsupported OS: ${RUNNER_OS}"
            exit 1
        fi

        ARCH=""
        if [[ $(uname -m) == "x86_64" ]]; then
            ARCH=amd64
        fi
        if [[ $(uname -m) == "aarch64" ]]; then
            ARCH=arm64
        fi

        FILE="slsactl_${VERSION#v}_${OS}_${ARCH}.tar.gz"

        echo "Installing ${FILE}"
        curl -LO "https://${REPO}/releases/download/${VERSION}/${FILE}"
        grep "${FILE}" "slsactl_${VERSION#v}_checksums.txt" | sha256sum -c
        tar -xf "${FILE}" slsactl
      else
        echo 'Version is not "latest" nor starts with "v". Fallback to go install with commit ID.'
        GOBIN=$(pwd) go install "github.com/rancherlabs/slsactl@${VERSION}"
      fi

      if sudo -l &> /dev/null; then
        sudo install -m 755 slsactl /usr/local/bin/slsactl
      else
        install -m 755 slsactl /usr/local/bin/slsactl
      fi
      
      rm -f "slsactl_${VERSION#v}_checksums.txt" "slsactl_${VERSION#v}_checksums.txt.sigstore.json" "${FILE}" slsactl
    env:
      VERSION: ${{ inputs.version }}
      REPO: github.com/rancherlabs/slsactl

  - name: Print version
    shell: bash
    run: |
      echo "slsactl installed:"
      slsactl version
