# This GitHub action verifies whether a given image has been signed using
# the cosign signature specification.
#
# This is meant to be used for Rancher Prime, or CNCF images that are part
# of the Rancher ecosystem.
#
# Reference usage:
#    steps:
#      ...
#      - uses: rancherlabs/slsactl/actions/verify@main
#        with:
#          image: <registry>/<image>:<tag>
#          certIdentityWorkflow: <workflow-name>

name: verify

inputs:
  image:
    description: |
      The image name component in a fully qualified image. For reference:
      <registry>/<repo>/<image>:<tag>.
    required: true
    type: string
  certIdentityWorkflow:
    description: |
      The workflow name to run for cert identity verification(only for images built for upstream projects).
    default: ""

runs:
  using: composite

  steps:
  - uses: actions/setup-go@v5
    with:
      go-version: 'stable'

  - name: Install slsactl
    shell:
    run: |
      go install github.com/rancherlabs/slsactl@latest

  - name: Verify image
    shell: bash
    run: |
      if [[ -n "${{ env.CERT_IDENTITY_WORKFLOW }}" ]]; then
        slsactl verify upstream --certIdentityWorkflow="${{ env.CERT_IDENTITY_WORKFLOW }}" ${{ env.IMAGE }}
      else
        slsactl verify ${{ env.IMAGE }}
      fi
    env:
      IMAGE: ${{ inputs.image }}
      CERT_IDENTITY_WORKFLOW: ${{ inputs.certIdentityWorkflow }}
